# Use the official Python image as the base image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements file
COPY ../requirements.txt ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt -r worker.reqs.txt

# Copy the rest of the application code
COPY . .

# Command to run the application
CMD ["python", "worker.py"] 