# Use the official Python image as the base image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements file
COPY requirements.txt ./

# Copy files in requests_log
COPY requests_log ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt -r requests_log.requirements.txt

# Expose the port the app runs on
EXPOSE 5003

# Command to run the application
CMD ["python", "requests_log.py"] 